name: cicd

on:
  workflow_dispatch:
      inputs:
          environments: 
              description: This is the environment where the workflow runs 
              type: choice
              default: dev 
              required: true
              options:
                  - dev 
                  - prod
                  - staging 

jobs:
  Code:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        run: echo "Code Clone from Github"

  Build:
    needs: [Code]
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker container
        run: echo "Docker Container Build"

  Test:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Test the Container
        run: echo "Testing the container"

  Deploy:
    if: inputs.environments == 'dev' 
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the App
        run: echo "Docker compose deployed the app"
